export const menuListData: any[] = [
  {
    id: 1,
    name: "系统总览",
    type: 1,
    url: "/main/analysis",
    icon: "Search",
    sort: 1,
    children: [
      {
        id: 2,
        url: "/main/analysis/dashboard",
        name: "指示信息",
        sort: 106,
        type: 2,
        children: null,
        parentId: 1,
      },
      {
        id: 3,
        url: "/main/analysis/overview",
        name: "核心技术",
        sort: 107,
        type: 2,
        children: null,
        parentId: 1,
      },
    ],
  },
  {
    id: 4,
    name: "商品中心",
    type: 1,
    url: "/main/product",
    icon: "Search",
    sort: 1,
    children: [
      {
        id: 5,
        url: "/main/product/category",
        name: "商品分类",
        sort: 108,
        type: 2,
        children: null,
        parentId: 4,
      },
      {
        id: 6,
        url: "/main/product/goods",
        name: "商品列表",
        sort: 106,
        type: 2,
        children: null,
        parentId: 4,
      },
    ],
  },
  {
    id: 7,
    name: "随便聊聊",
    type: 1,
    url: "/main/story",
    icon: "Search",
    sort: 1,
    children: [
      {
        id: 8,
        url: "/main/story/chat",
        name: "核心技术",
        sort: 106,
        type: 2,
        children: null,
        parentId: 7,
      },
      {
        id: 9,
        url: "/main/story/list",
        name: "聊天列表",
        sort: 106,
        type: 2,
        children: null,
        parentId: 7,
      },
    ],
  },
  {
    id: 10,
    name: "系统管理",
    type: 1,
    url: "/main/system",
    icon: "Search",
    sort: 1,
    children: [
      {
        id: 11,
        url: "/main/system/department",
        name: "部门管理",
        sort: 106,
        type: 2,
        children: null,
        parentId: 10,
      },
      {
        id: 12,
        url: "/main/system/menu",
        name: "菜单管理",
        sort: 106,
        type: 2,
        children: null,
        parentId: 10,
      },
      {
        id: 13,
        url: "/main/system/role",
        name: "角色管理",
        sort: 106,
        type: 2,
        parentId: 10,
        children: [
          {
            id: 16,
            url: "/main/system/role",
            name: "创建角色",
            sort: 106,
            type: 3,
            children: null,
            parentId: 10,
            permission: "system:role:create",
          },
          {
            id: 17,
            url: "/main/system/role",
            name: "删除角色",
            sort: 106,
            type: 3,
            children: null,
            parentId: 10,
            permission: "system:role:delete",
          },
          {
            id: 18,
            url: "/main/system/role",
            name: "修改角色",
            sort: 106,
            type: 3,
            children: null,
            parentId: 10,
            permission: "system:role:update",
          },
          {
            id: 19,
            url: "/main/system/role",
            name: "查询角色",
            sort: 106,
            type: 3,
            children: null,
            parentId: 10,
            permission: "system:role:query",
          },
        ],
      },
      {
        id: 14,
        url: "/main/system/user",
        name: "用户管理",
        sort: 106,
        type: 2,
        parentId: 10,
        children: [
          {
            id: 16,
            url: "/main/system/role",
            name: "创建用户",
            sort: 106,
            type: 3,
            children: null,
            parentId: 14,
            permission: "system:users:create",
          },
          {
            id: 17,
            url: "/main/system/role",
            name: "删除用户",
            sort: 106,
            type: 3,
            children: null,
            parentId: 14,
            permission: "system:users:delete",
          },
          {
            id: 18,
            url: "/main/system/role",
            name: "修改用户",
            sort: 106,
            type: 3,
            children: null,
            parentId: 14,
            permission: "system:users:update",
          },
          {
            id: 19,
            url: "/main/system/role",
            name: "查询用户",
            sort: 106,
            type: 3,
            children: null,
            parentId: 14,
            permission: "system:users:query",
          },
        ],
      },
    ],
  },
];
